In [117]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [118]:
df = pd.read_csv('Maternal Health Risk Data Set.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [119]:
print(X)

[[ 25. 130.  80.  15.  98.  86.]
 [ 35. 140.  90.  13.  98.  70.]
 [ 29.  90.  70.   8. 100.  80.]
 ...
 [ 35.  85.  60.  19.  98.  86.]
 [ 43. 120.  90.  18.  98.  70.]
 [ 32. 120.  65.   6. 101.  76.]]


In [120]:
print(y)

['high risk' 'high risk' 'high risk' ... 'high risk' 'high risk'
 'mid risk']


In [121]:
from sklearn.impute import SimpleImputer
flag = False
for i in df.columns.tolist():
    if ('?' in df[i].tolist() or '' in df[i].tolist()):
        print(f'There are missing values in {i} row, please check it')
        flag = True
print(flag)

False


In [122]:
tmp = df.isnull()
tmp.head()

Age  SystolicBP  DiastolicBP     BS  BodyTemp  HeartRate  RiskLevel
0  False       False        False  False     False      False      False
1  False       False        False  False     False      False      False
2  False       False        False  False     False      False      False
3  False       False        False  False     False      False      False
4  False       False        False  False     False      False      False

In [123]:
for i in tmp.columns.tolist():
    print(tmp[i].value_counts())
    print('')

Age
False    1014
Name: count, dtype: int64

SystolicBP
False    1014
Name: count, dtype: int64

DiastolicBP
False    1014
Name: count, dtype: int64

BS
False    1014
Name: count, dtype: int64

BodyTemp
False    1014
Name: count, dtype: int64

HeartRate
False    1014
Name: count, dtype: int64

RiskLevel
False    1014
Name: count, dtype: int64



In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          1014 non-null   int64  
 1   SystolicBP   1014 non-null   int64  
 2   DiastolicBP  1014 non-null   int64  
 3   BS           1014 non-null   float64
 4   BodyTemp     1014 non-null   float64
 5   HeartRate    1014 non-null   int64  
 6   RiskLevel    1014 non-null   object 
dtypes: float64(2), int64(4), object(1)
memory usage: 55.6+ KB


In [125]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [126]:
print(np.unique(y))

['high risk' 'low risk' 'mid risk']


In [127]:
for i in range(len(y)):
    if y[i] == 'high risk':
        y[i] = 0
    elif y[i] == 'low risk':
        y[i] = 1
    elif y[i] == 'mid risk':
        y[i] = 2

In [128]:
print(y)

[0 0 0 ... 0 0 2]


In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LogisticRegression
polyFeatures = PolynomialFeatures(degree=4)
X_poly = polyFeatures.fit_transform(X)
logisticReg = LogisticRegression()
logisticReg.fit(X_poly, y)
y_pred = logisticReg.predict(X_poly)    