In [1]:
import numpy as np
import time

In [5]:
a = np.zeros(4)
print(a)
a = np.random.random_sample(4)
print(a)

[0. 0. 0. 0.]
[0.33394942 0.85411834 0.30990816 0.15391684]


In [10]:
print(a.shape)
print(a.dtype)

(4,)
float64


In [14]:
a = np.arange(4)
print(a)
print(a.dtype)

[0 1 2 3]
int64


In [15]:
a = np.array([5, 4, 3, 2, 1])
print(a)

[5 4 3 2 1]
