In [94]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot')
matplotlib.use('TkAgg')

In [95]:
data = pd.read_csv('Position_Salaries.csv')
X = np.array(data.iloc[:, 1:2].values)
y = np.array(data.iloc[:, -1].values)

In [96]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X = imputer.fit_transform(X)

In [97]:
print(X)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


In [98]:
from sklearn.tree import DecisionTreeRegressor
regressor_1 = DecisionTreeRegressor(max_depth=2)
regressor_1.fit(X, y)
regressor_2 = DecisionTreeRegressor(max_depth=5)
regressor_2.fit(X,y)
regressor_3 = DecisionTreeRegressor()
regressor_3.fit(X,y)

DecisionTreeRegressor()

In [99]:
regressor_1.predict([[6.5]])

array([82500.])

In [100]:
regressor_2.predict([[6.5]])

array([150000.])

In [101]:
regressor_3.predict([[6.5]])

array([150000.])

In [102]:
plt.scatter(X, y, color='red')
plt.plot(X, regressor_1.predict(X), color='blue')
plt.plot(X, regressor_2.predict(X), color='orange')
plt.plot(X, regressor_3.predict(X), color='purple')
plt.xlabel('PositionLevel')
plt.ylabel('Salary')
plt.title('Decision tree')
plt.show()

In [103]:
X_grid = np.arange(X.min(), X.max(), 0.1)
X_grid = X_grid.reshape(-1, 1)
print(X_grid)

[[1. ]
 [1.1]
 [1.2]
 [1.3]
 [1.4]
 [1.5]
 [1.6]
 [1.7]
 [1.8]
 [1.9]
 [2. ]
 [2.1]
 [2.2]
 [2.3]
 [2.4]
 [2.5]
 [2.6]
 [2.7]
 [2.8]
 [2.9]
 [3. ]
 [3.1]
 [3.2]
 [3.3]
 [3.4]
 [3.5]
 [3.6]
 [3.7]
 [3.8]
 [3.9]
 [4. ]
 [4.1]
 [4.2]
 [4.3]
 [4.4]
 [4.5]
 [4.6]
 [4.7]
 [4.8]
 [4.9]
 [5. ]
 [5.1]
 [5.2]
 [5.3]
 [5.4]
 [5.5]
 [5.6]
 [5.7]
 [5.8]
 [5.9]
 [6. ]
 [6.1]
 [6.2]
 [6.3]
 [6.4]
 [6.5]
 [6.6]
 [6.7]
 [6.8]
 [6.9]
 [7. ]
 [7.1]
 [7.2]
 [7.3]
 [7.4]
 [7.5]
 [7.6]
 [7.7]
 [7.8]
 [7.9]
 [8. ]
 [8.1]
 [8.2]
 [8.3]
 [8.4]
 [8.5]
 [8.6]
 [8.7]
 [8.8]
 [8.9]
 [9. ]
 [9.1]
 [9.2]
 [9.3]
 [9.4]
 [9.5]
 [9.6]
 [9.7]
 [9.8]
 [9.9]]


In [104]:
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor_1.predict(X_grid), color='blue')
plt.plot(X_grid, regressor_2.predict(X_grid), color='orange')
plt.plot(X_grid, regressor_3.predict(X_grid), color='purple')
plt.xlabel('PositionLevel')
plt.ylabel('Salary')
plt.title('Decision tree')
plt.show()